// This file is automatically generated. Do not edit it directly.
import { localClient } from '@/integrations/local/client';

// Export local client as supabase for compatibility
export const supabase = localClient;